#!/usr/bin/env python3
"""
Audit TACO/SFT data before SFT or GRPO.

Default mode audits JSONL generated by scripts/build_sft_dataset.py:
    python scripts/audit_sft_data.py --data data/sft_train.jsonl --top-k 20

Optional loader mode samples local TACO through src.data.loader:
    python scripts/audit_sft_data.py --from-loader --limit 1000
"""

from __future__ import annotations

import argparse
import json
import statistics
import sys
from collections import Counter
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))


def _as_list(value: Any) -> list:
    if value is None:
        return []
    if isinstance(value, list):
        return value
    return [value]


def _median(values: list[int]) -> float:
    if not values:
        return 0.0
    return float(statistics.median(values))


def _avg(values: list[int]) -> float:
    if not values:
        return 0.0
    return sum(values) / len(values)


def _empty_stats() -> dict[str, Any]:
    return {
        "total": 0,
        "standard_input": 0,
        "call_based": 0,
        "unknown_io": 0,
        "reward_compatible": 0,
        "interactive": 0,
        "difficulty": Counter(),
        "skill_types": Counter(),
        "tags": Counter(),
        "test_case_counts": [],
    }


def _update_stats(stats: dict[str, Any], meta: dict[str, Any]) -> None:
    stats["total"] += 1

    io_mode = meta.get("io_mode") or "unknown"
    if io_mode == "standard_input":
        stats["standard_input"] += 1
    elif io_mode == "call_based":
        stats["call_based"] += 1
    else:
        stats["unknown_io"] += 1

    if meta.get("reward_compatible") is True:
        stats["reward_compatible"] += 1

    difficulty = str(meta.get("difficulty") or "unknown")
    stats["difficulty"][difficulty] += 1

    for skill in _as_list(meta.get("skill_types")):
        stats["skill_types"][str(skill)] += 1

    for tag in _as_list(meta.get("tags")):
        stats["tags"][str(tag)] += 1

    raw_tags = [str(t).lower() for t in _as_list(meta.get("raw_tags"))]
    if "interactive" in raw_tags:
        stats["interactive"] += 1

    test_cases = meta.get("test_cases") or []
    stats["test_case_counts"].append(len(test_cases) if isinstance(test_cases, list) else 0)


def audit_jsonl(path: Path) -> dict[str, Any]:
    if not path.exists():
        raise FileNotFoundError(f"SFT JSONL 不存在：{path}")

    stats = _empty_stats()
    with path.open(encoding="utf-8") as f:
        for line_no, line in enumerate(f, 1):
            line = line.strip()
            if not line:
                continue
            try:
                obj = json.loads(line)
            except json.JSONDecodeError as exc:
                raise ValueError(f"JSON 解析失败：{path}:{line_no}: {exc}") from exc
            _update_stats(stats, obj.get("metadata", {}))
    return stats


def audit_loader(limit: int, taco_data_root: str, split: str) -> dict[str, Any]:
    from src.data.loader import load_problems
    from src.reward.execution import supports_verification

    stats = _empty_stats()
    problems = load_problems(
        source="taco",
        split=split,
        max_items=limit,
        deduplicate=False,
        taco_data_root=taco_data_root,
    )
    for p in problems:
        input_output = p.input_output if isinstance(p.input_output, dict) else {}
        io_mode = "call_based" if input_output.get("fn_name") else "standard_input"
        test_cases = p.public_tests or []
        meta = {
            "difficulty": p.difficulty,
            "tags": p.tags,
            "raw_tags": p.raw_tags,
            "skill_types": p.skill_types,
            "io_mode": io_mode,
            "fn_name": input_output.get("fn_name"),
            "starter_code": p.starter_code,
            "test_cases": test_cases,
        }
        meta["reward_compatible"] = supports_verification(meta)
        _update_stats(stats, meta)
    return stats


def _print_counter(title: str, counter: Counter, top_k: int | None = None) -> None:
    print(f"\n{title}")
    items = counter.most_common(top_k)
    if not items:
        print("  (empty)")
        return
    for key, count in items:
        print(f"  {key}: {count}")


def print_report(stats: dict[str, Any], top_k: int) -> None:
    total = stats["total"]
    reward_n = stats["reward_compatible"]
    interactive_n = stats["interactive"]
    tc_counts = stats["test_case_counts"]

    print("=== TACO/SFT Data Audit ===")
    print(f"total records: {total}")
    print(f"standard_input count: {stats['standard_input']}")
    print(f"call_based count: {stats['call_based']}")
    print(f"unknown io_mode count: {stats['unknown_io']}")
    print(f"reward_compatible count: {reward_n}")
    print(f"reward_compatible ratio: {reward_n / total:.4f}" if total else "reward_compatible ratio: 0.0000")
    print(f"raw_tags interactive count: {interactive_n}")
    print(f"raw_tags interactive ratio: {interactive_n / total:.4f}" if total else "raw_tags interactive ratio: 0.0000")

    print("test_cases stats:")
    print(f"  avg: {_avg(tc_counts):.2f}")
    print(f"  median: {_median(tc_counts):.2f}")
    print(f"  min: {min(tc_counts) if tc_counts else 0}")
    print(f"  max: {max(tc_counts) if tc_counts else 0}")

    _print_counter("difficulty distribution", stats["difficulty"])
    _print_counter("skill_types distribution", stats["skill_types"])
    _print_counter(f"tags Top-{top_k}", stats["tags"], top_k=top_k)


def main() -> None:
    parser = argparse.ArgumentParser(description="Audit TACO/SFT JSONL or local TACO loader")
    parser.add_argument("--data", type=Path, default=Path("data/sft_train.jsonl"))
    parser.add_argument("--top-k", type=int, default=20)
    parser.add_argument("--from-loader", action="store_true", help="审计 loader 层样本，而不是 SFT JSONL")
    parser.add_argument("--limit", type=int, default=1000, help="--from-loader 模式下加载数量")
    parser.add_argument("--split", choices=["train", "test"], default="train")
    parser.add_argument("--taco-data-root", default="data/raw/TACO/ALL")
    args = parser.parse_args()

    if args.from_loader:
        stats = audit_loader(args.limit, args.taco_data_root, args.split)
    else:
        stats = audit_jsonl(args.data)
    print_report(stats, args.top_k)


if __name__ == "__main__":
    main()
